_BASE_: "../Base-RCNN.yaml"
MODEL:
  META_ARCHITECTURE: "GeneralizedRCNN"
  WEIGHTS: "/home/wxq/od/DeFRCN/ImageNetPretrained/MSRA/R-101.pkl"
  MASK_ON: False
  BACKBONE:
    FREEZE: False
  RESNETS:
    DEPTH: 101
  RPN:
    # ENABLE_DECOUPLE: True
    # BACKWARD_SCALE: 0.0
    FREEZE: False
  ROI_HEADS:
    NUM_CLASSES: 9
    # ENABLE_DECOUPLE: True
    # BACKWARD_SCALE: 0.75
    FREEZE_FEAT: False
    # ???可以调一下
    CLS_DROPOUT: True
INPUT:
  #???
  # MIN_SIZE_TRAIN: (480, 512, 544, 576, 608, 640, 672, 704, 736, 768, 800)
  MIN_SIZE_TRAIN: (640, 672, 704, 736, 768, 800)
  #???
  MIN_SIZE_TEST: 800
DATASETS:
  #???
  TRAIN: ("laf_trainval_novel2_2shot_seed1", )
  TEST: ("laf_test_2",)
DATALOADER:
    NUM_WORKERS: 0
SOLVER:
  IMS_PER_BATCH: 16
  # 调一下
  BASE_LR: 0.02
  # 调一下,后期根据不同shot要调
  STEPS: (4000, 6000)
  MAX_ITER: 8000
  CHECKPOINT_PERIOD: 8000
#  STEPS: (8000, 10000)
#  MAX_ITER: 10000
#  CHECKPOINT_PERIOD: 10000
  WARMUP_ITERS: 100
TEST:
  # 调一下
  PCB_ENABLE: False
  EVAL_PERIOD: 1000
DYNAMIC:
  ALPHA: 3
  BETA: 0.99
  # 设为0等价于 epsilon=alpha
  C: 0.2
  EPSILON: 1